# Generated by Django 5.2.4 on 2025-08-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location_lng',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
