# Generated by Django 5.2.4 on 2025-08-05 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_location_lat_remove_user_location_lng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='location_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='location_lng',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
