# Generated by Django 5.2.4 on 2025-08-05 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_location_lat_pharmacy_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='latitude',
            new_name='location_lat',
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='longitude',
            new_name='location_lng',
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
