# Generated by Django 5.2.4 on 2025-08-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_latitude_pharmacy_location_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='location_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='location_lng',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_pharmacy',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('pharmacy', 'pharmacy'), ('user', 'user')], default='user', max_length=20),
        ),
    ]
